Refactor to avoid using the BOARD cmake variable
astarte-platform/astarte-device-sdk-zephyr pull request #192
Opened 2024-09-20 13:02 UTC by lucaato

2024-09-24 15:41 UTC, harlem88 approved these changes

2024-09-26 15:37 UTC, lucaato commented
Rebased onto release... since the BOARD variable we were using is not a supported variable a module's CMakeLists should be reading we should probably merge this pr also on the 0.7 release to avoid future problems.

2024-10-10 09:15 UTC, sorru94 commented on samples/common/CommonComponents.cmake
>  FILE(GLOB app_common_sources ${CMAKE_CURRENT_LIST_DIR}/src/*.c)
Yes, I agree

2024-10-10 09:21 UTC, lucaato commented on samples/common/CommonComponents.cmake
>  FILE(GLOB app_common_sources ${CMAKE_CURRENT_LIST_DIR}/src/*.c)
Wasn't sure myself, but there are still components that are shared with the e2e test (take a look at the CMakeLists.txt), and even some integration tests include some files like the generated interfaces (tests/lib/astarte_device_sdk/integration/device_caching/CMakeLists.txt).
So I didn't feel like including them directly from the `astarte_app` folder would be a good thing. Another idea could be to rename the common folder to something more desrciptive like `shared`. Let me know if you prefer including everything from the sample folder.

2024-10-10 10:00 UTC, sorru94 requested changes

2024-10-10 10:02 UTC, harlem88 commented on samples/common/CommonComponents.cmake
>  FILE(GLOB app_common_sources ${CMAKE_CURRENT_LIST_DIR}/src/*.c)
Ok if it is shared with `e2etst` and `test`, it is to keep `common` folder.

2024-10-10 12:26 UTC, lucaato commented on samples/common/CommonComponents.cmake
>  FILE(GLOB app_common_sources ${CMAKE_CURRENT_LIST_DIR}/src/*.c)
mhh i'm not sure, it's even more confusing if it's shared from a random sample just because it happens to use the same file. I mean it's not like the user cares about the common folder, it's more of a thing that we use to keep files organized. And including stuff that belongs to a sample from the e2e or a test is not great imo

2024-10-10 12:52 UTC, lucaato commented on samples/astarte_app/src/main.c
> +struct created_device
I don't like when threads are able to stop each other so i think I will send a NULL pointer as error to avoid having to abort the other thread.

2024-10-10 12:54 UTC, lucaato commented on samples/astarte_app/src/main.c
> +}
I've used the function since the user can immediately understand what is happening, without even requiring a comment and also because it will probably need to use them in its code to ensure.

2024-10-10 12:55 UTC, lucaato commented on samples/astarte_app/src/main.c
> +        k_msgq_put(&device_msgq, &(struct created_device) {}, K_FOREVER);
as above

2024-10-14 06:33 UTC, sorru94 commented on samples/astarte_app/src/main.c
> +struct created_device
Sure, sending a NULL pointer is fine as well.
But do not exclude stopping threads from other threads by defaults. Often it's the easiest and cleanest solution.

2024-10-14 06:36 UTC, sorru94 commented on samples/astarte_app/src/main.c
> +}
The user needs to scroll to find the content of such a function, which is much more complex than having the while statement inline.
Short functions used only in one spot are generally avoided because they require jumping around in the file, making the code less readable.

2024-10-14 07:19 UTC, sorru94 requested changes

2024-10-14 07:19 UTC, sorru94 commented on samples/astarte_app/Kconfig
> +        WiFi password (WPA or WPA2) for the example to use.
We could make those depend on `WIFI` being enabled.

2024-10-14 07:19 UTC, sorru94 commented on samples/astarte_app/README.md
> +the connection status.
From this line being in the registration section it looks like the connection will only be performed if the registration is enabled.
I would just state in one of the sections above that connection and disconnection as well as the callbacks are always enabled.

2024-10-14 07:19 UTC, sorru94 commented on samples/astarte_app/README.md
> +### Individuals
The following sections are a little confusing it appears from the `Sample configurable steps` title that the ones here are the ones you can enable or disable. But the sections below only describe how to send data to the device through Astarte and observe the callbacks.

2024-10-14 07:19 UTC, sorru94 commented on samples/astarte_app/README.md
> +- `43` The device unsets the device owned properties set with `41`
This is probably left over from an old sample. Correct?

2024-10-14 09:46 UTC, lucaato commented on samples/astarte_app/README.md
> +### Individuals
Tried to solve it let me know what you think

2024-10-14 09:56 UTC, lucaato commented on samples/common/CommonComponents.cmake
>  FILE(GLOB app_common_sources ${CMAKE_CURRENT_LIST_DIR}/src/*.c)
Since the common folder uses way less custom cmake logic than before I think it could also work with custom plugins. Until we are actually sure it does not work i would keep it separated.

2024-10-14 14:21 UTC, sorru94 requested changes
All the samples are from the point of view of the device. 
So transmission is from the device to Astarte. Reception is from Astarte to the device.

2024-10-14 14:21 UTC, sorru94 commented on samples/astarte_app/README.md
> +### Individuals reception
I think you mean `Individuals transmission` here right?

2024-10-14 14:21 UTC, sorru94 commented on samples/astarte_app/README.md
> +### Send server datastream data
```suggestion
### Reception of individal datastream data
```

2024-10-14 14:21 UTC, sorru94 commented on samples/astarte_app/README.md
> +data to the device.
```suggestion
data from Astarte to the device. Then observe the reception callback being triggered on the device.
```

2024-10-14 14:21 UTC, sorru94 commented on samples/astarte_app/README.md
> +device is:
```suggestion
By changing the endpoint and payload in the astartectl command other data types can be transmitted to the device.
```

2024-10-14 14:21 UTC, sorru94 commented on samples/astarte_app/README.md
> +
```suggestion
Check out all the endpoints available in the interfaces provided with the sample.

```

2024-10-14 15:12 UTC, sorru94 approved these changes

2024-10-14 15:42 UTC, harlem88 requested changes

2024-10-14 15:42 UTC, harlem88 commented on samples/README.md
> +The interfaces are defined in JSON filed sontained in the `common/interfaces` folder.
```suggestion
The interfaces are defined in JSON files contained in the `common/interfaces` folder.
```

2024-10-14 15:42 UTC, harlem88 commented on samples/astarte_app/README.md
> +device and server behaviour. Kconfig values contol the compilation of these steps, here
```suggestion
device and server behaviour. Kconfig values control the compilation of these steps, here
```

2024-10-14 15:42 UTC, harlem88 commented on samples/astarte_app/README.md
> +We recomend storing the JWT in a shell variable to access it with ease.
```suggestion
We recommend storing the JWT in a shell variable to access it with ease.
```

2024-10-14 15:42 UTC, harlem88 commented on samples/astarte_app/README.md
> +We recomend storing the JWT in a shell variable to access it with ease.
```suggestion
We recommend storing the JWT in a shell variable to access it with ease.
```

2024-10-14 15:42 UTC, harlem88 commented on samples/astarte_app/README.md
> +We recomend storing the JWT in a shell variable to access it with ease.
```suggestion
We recommend storing the JWT in a shell variable to access it with ease.
```

2024-10-15 13:58 UTC, sorru94 requested changes

2024-10-15 13:58 UTC, sorru94 commented on samples/astarte_app/Kconfig
> +    default 2048
This is not sufficient. Bring it up to `4096`

2024-10-15 14:04 UTC, sorru94 commented on samples/astarte_app/boards/native_sim.conf
> +#
I would add a small section in the README regarding the steps necessary to run this sample on native sim

2024-10-15 15:22 UTC, sorru94 reviewed
The option for `native_sim` `CONFIG_LOG_BUFFER_SIZE` defined in `native_sim.conf` can be removed as it's only needed for deferred logging.

2024-10-15 16:22 UTC, sorru94 commented on samples/astarte_app/boards/mimxrt1060_evkb.conf
I would add this:
```
# Since there is no permanent storage, properties are of little use on this board
CONFIG_DEVICE_PROPERTY_SET_TRANSMISSION=y
CONFIG_DEVICE_PROPERTY_UNSET_TRANSMISSION=y
```

2024-10-16 12:30 UTC, sorru94 approved these changes

2024-10-16 12:31 UTC, harlem88 approved these changes

2024-10-16 14:19 UTC, merged