Replace regex in mappings
astarte-platform/astarte-device-sdk-zephyr pull request #199
Opened 2024-09-26 11:04 UTC by sorru94

2024-09-27 15:52 UTC, harlem88 requested changes

2024-09-27 15:52 UTC, harlem88 commented on lib/astarte_device_sdk/mapping.c
> +    // The check will differ is the segment is a paramete or not
```suggestion
    // The check will differ is the segment is a parameter or not
```

2024-09-30 14:08 UTC, sorru94 commented on lib/astarte_device_sdk/mapping.c
> +        return ASTARTE_RESULT_MAPPING_PATH_MISMATCH;
Since this function is called within loops I would avoid logging even in debug mode as it easily clogs the logging buffers. In addition, this function is expected to return a mismatch more than a match as it's used to find a mapping conforming to a path.

2024-09-30 14:11 UTC, sorru94 commented on lib/astarte_device_sdk/mapping.c
> +    }
The loop can terminate in three ways:
- We run out of endpoint segments
- We run out of path segments
- We run out of both path and endpoint segments
The third option is the only one that results in this 'if' condition not being true.

2024-09-30 14:30 UTC, lucaato commented on lib/astarte_device_sdk/mapping.c
> +        return ASTARTE_RESULT_MAPPING_PATH_MISMATCH;
Yes but with the regexes it was easy to verify why your event handler was not being called, how would you suggest a user should debug this ? should we make it simpler to debug ?

2024-09-30 14:39 UTC, lucaato commented on lib/astarte_device_sdk/mapping.c
> +    }
my bad, didn't check well enough

2024-09-30 14:43 UTC, lucaato commented on lib/astarte_device_sdk/mapping.c
> +}
If we don't need return codes or anything like that this function could return a boolean.

2024-09-30 16:02 UTC, harlem88 requested changes

2024-09-30 16:02 UTC, harlem88 commented on lib/astarte_device_sdk/mapping.c
> +        }
What do you think to use a single `if`?
```suggestion
        if ((endpoint_segment_len != path_segment_len) || (memcmp(endpoint_start, path_start, path_segment_len) != 0) {
            return ASTARTE_RESULT_MAPPING_PATH_MISMATCH;
        }
```

2024-10-01 08:01 UTC, sorru94 commented on lib/astarte_device_sdk/mapping.c
> +        return ASTARTE_RESULT_MAPPING_PATH_MISMATCH;
The calls to this function should handle the logging

2024-10-01 09:11 UTC, lucaato approved these changes

2024-10-01 12:25 UTC, harlem88 approved these changes

2024-10-01 15:18 UTC, merged