Ensuing synchronization with Astarte
astarte-platform/astarte-device-sdk-zephyr pull request #203
Opened 2024-10-03 12:48 UTC by sorru94

2024-10-03 15:24 UTC, lucaato commented on lib/astarte_device_sdk/device_connection.c
> +static int send_purge_device_properties(astarte_device_handle_t device)
Like the other case, why you decided to use an int as result type

2024-10-03 16:15 UTC, harlem88 commented on lib/astarte_device_sdk/device_caching.c
> +        = { 0 };
Have you considered to use an int value or Enum? So you can compare without use a `strncmp` in the line below.

2024-10-04 07:43 UTC, sorru94 commented on lib/astarte_device_sdk/device_connection.c
> +static int setup_subscriptions(astarte_device_handle_t device)
Sure, it does not really matter in this instance as there is a single possible reaction to those operations, independently from the error source.
However, I agree that it looks better as an Astarte result.

2024-10-04 08:55 UTC, sorru94 commented on lib/astarte_device_sdk/device_caching.c
> +        = { 0 };
I think I'll make it a boolean. I would not expect it to create confusion regarding the meaning.

2024-10-04 16:16 UTC, harlem88 requested changes

2024-10-04 16:16 UTC, harlem88 commented on lib/astarte_device_sdk/device_caching.c
> +    }
What do you think to leave only the log in the if block?

```suggestion
    if (!read_sync) {
        ASTARTE_LOG_INF("No previous synchronization with Astarte present.");
    }
    *sync = read_sinc;
```

2024-10-04 16:16 UTC, harlem88 commented on lib/astarte_device_sdk/device.c
> +    handle->synchronization_completed = synchronization_completed;
Use `synchronization_completed` directly from handle, without allocate different variable.
```suggestion
    handle->synchronization_completed = false;
#if defined(CONFIG_ASTARTE_DEVICE_SDK_PERMANENT_STORAGE)
    ares = astarte_device_caching_synchronization_get(&handle->synchronization_completed);
    if ((ares != ASTARTE_RESULT_OK) && (ares != ASTARTE_RESULT_NOT_FOUND)) {
        ASTARTE_LOG_ERR("Synchronization state getter failure %s.", astarte_result_to_name(ares));
        goto failure;
    }
#endif
```

2024-10-07 08:32 UTC, harlem88 approved these changes

2024-10-07 08:48 UTC, lucaato approved these changes

2024-10-07 12:22 UTC, merged