Blocking disconnect function
astarte-platform/astarte-device-sdk-zephyr pull request #212
Opened 2024-11-07 16:13 UTC by sorru94

2024-11-11 12:06 UTC, harlem88 requested changes

2024-11-11 12:06 UTC, harlem88 commented on include/astarte_device_sdk/device.h
> +    astarte_device_handle_t device, k_timeout_t timeout, bool force);
Since If It passed a timeout the function has a different behavior, What do you think to separate in two different function?
``` c
astarte_result_t astarte_device_disconnect(
    astarte_device_handle_t device, bool force);
astarte_result_t astarte_device_disconnect_with_timeout(
    astarte_device_handle_t device, k_timeout_t timeout);
```

2024-11-12 08:21 UTC, sorru94 commented on include/astarte_device_sdk/device.h
> +    astarte_device_handle_t device, k_timeout_t timeout, bool force);
The `force` flag would be unnecessary in the first function, making a forced disconnection the default.
I think the disconnect function should not default to disconnecting the device disregarding pending QoS 1 and 2 messages.
I prefer having a single function with a force argument to clarify what the function does.
Another option would be to keep the force argument in the disconnect function and return an error when force is not set and there are pending messages.

2024-11-12 08:57 UTC, lucaato commented on include/astarte_device_sdk/device.h
> +    astarte_device_handle_t device, k_timeout_t timeout, bool force);
I would split them in a different way to avoid having the force boolean. The inner workings should be the same but without the bool parameter.
```suggestion
// does not block and disconnects the client imediately
astarte_result_t astarte_device_force_disconnect(
    astarte_device_handle_t device);
// wait that messages get sent or for the specified timeout 
astarte_result_t astarte_device_disconnect(
    astarte_device_handle_t device, k_timeout_t timeout);
```
This way we avoid having weird situations where a user could define a timeout even if it is unused because force is true.

2024-11-12 09:54 UTC, sorru94 commented on include/astarte_device_sdk/device.h
> +    astarte_device_handle_t device, k_timeout_t timeout, bool force);
I think this could be a good middle ground, clear enough for the user to understand while still separating the functions.

2024-11-12 13:33 UTC, harlem88 approved these changes

2024-11-12 15:05 UTC, sorru94 commented on lib/astarte_device_sdk/device_connection.c
>      }
I can't understand your suggestion from this comment, it's too convoluted.

2024-11-13 08:18 UTC, merged