Refresh get started
astarte-platform/astarte-device-sdk-zephyr pull request #218
Opened 2024-12-03 16:33 UTC by sorru94

2024-12-06 16:40 UTC, lucaato requested changes

2024-12-06 16:40 UTC, lucaato commented on get_started.md
> +Copy it somewhere safe as it will be used in the next steps.
Even if using the dashboard it's a good exercise for newcomers I would still add somewhere that this can be done (faster maybe) with astartectl. If this is aimed at programmers some of them will be happy... probably.

2024-12-06 16:40 UTC, lucaato commented on get_started.md
>  ```
Keep a consistent indentation if possible. In this case spaces are probably better than tabs.

2024-12-06 16:40 UTC, lucaato commented on get_started.md
> +            k_sem_take(&ipv4_address_obtained, K_NO_WAIT);
Does decrementing the semaphore makes sense if the device is already after the sem take in the main ? What i mean is won't it proceed anyways ?

2024-12-06 16:40 UTC, lucaato commented on get_started.md
>  ```
It would be also cool to have a formatter that runs on this type of markdown embedded code but I don't know if those exist for c.

2024-12-09 08:32 UTC, sorru94 commented on get_started.md
> +Copy it somewhere safe as it will be used in the next steps.
I would keep it streamlined for a get-started and avoid confusing the first-time users with `astartectl` commands.
We can keep those ones in the readme of the ordinary samples.

2024-12-09 08:33 UTC, sorru94 commented on get_started.md
>  ```
Not that I know of. If you find one feel free to link to it and I'll add it.

2024-12-09 08:35 UTC, sorru94 commented on get_started.md
> +            k_sem_take(&ipv4_address_obtained, K_NO_WAIT);
It does not. Those are leftovers from the eth driver in which the decrement is used.

2024-12-09 08:35 UTC, lucaato commented on get_started.md
> +Copy it somewhere safe as it will be used in the next steps.
Just add a section about it at the end, so that it does not bother too much but it can still be looked up by who wants to learn more

2024-12-09 08:42 UTC, lucaato commented on get_started.md
>  ```
I found this one https://github.com/hougesen/mdsf but I never heard of it before, even if it seems mantained.

2024-12-09 08:58 UTC, sorru94 commented on get_started.md
> +            k_sem_take(&ipv4_address_obtained, K_NO_WAIT);
This is a leftover from the ethernet driver in which the reconnection is manual.

2024-12-09 15:52 UTC, harlem88 approved these changes

2024-12-09 16:38 UTC, harlem88 approved these changes

2024-12-09 16:41 UTC, merged