Add readme for nxp application hub
astarte-platform/astarte-device-sdk-zephyr pull request #220
Opened 2024-12-04 11:46 UTC by sorru94

2024-12-10 08:38 UTC, harlem88 requested changes

2024-12-10 08:38 UTC, harlem88 commented on samples/astarte_app/README_NXP.md
> +Click on register device, this will register the device an give you a credentials secret.
```suggestion
Click on register device, this will register the device and give you a credentials secret.
```

2024-12-10 09:58 UTC, harlem88 commented on samples/astarte_app/README_NXP.md
> +| 1.0     | Initial release on Application Code Hub        | October 23<sup>rd</sup> 2024 |
Should we have to update this date? Or is it related to Application Hub?
```suggestion
| 1.0     | Initial release on Application Code Hub        | October 23<sup>rd</sup> 2024 |
```

2024-12-10 10:34 UTC, sorru94 commented on samples/astarte_app/README_NXP.md
> +| 1.0     | Initial release on Application Code Hub        | October 23<sup>rd</sup> 2024 |
I think we will need to update this when we perform the release.

2024-12-11 10:31 UTC, lucaato approved these changes

2024-12-11 15:48 UTC, atsetilam reviewed
Fix minor typos; evaluate suggestions for readability.

2024-12-11 15:48 UTC, atsetilam commented on samples/astarte_app/README_NXP.md
> +Upon running the code the demo application will display on the serial monitor its progression.
... will display ~~on the serial monitor its progression~~ **its progress on the serial monitor**.

2024-12-11 15:48 UTC, atsetilam commented on samples/astarte_app/README_NXP.md
> +The easiest way to set up one is to follow the
inverting the order as **set one up** might improve readability.

2024-12-12 08:15 UTC, sorru94 commented on samples/astarte_app/README.md
> +Data like wifi passwords or even the astarte credential secret could be configured in a
In my opinion, there is an issue with capitalization in the Astarte documentation. Excessive capitalization is present throughout the documentation, making it much harder to read than it should be. 
For example in the page you linked, the first paragraph has more than one in 5 capitalized.

2024-12-13 11:09 UTC, harlem88 approved these changes

2024-12-13 11:09 UTC, merged